### ISSUE TITLE
target = "javascript",  integer value is too large

### ISSUE THREAD

**Issue by denegny** [hunkyjimpjorps/rememo#1]
`gleam fix`

  { name = "rememo", version = "3.0.0"

```
This integer value is too large to be represented accurately by
JavaScript's number type. To avoid this warning integer values must be in
the range -(2^53 - 1) - (2^53 - 1)
```

**Comment by hunkyjimpjorps** [comment]
This looks like an issue caused by the `youid` package, which is only used for the Erlang target, but I'm not sure how to suppress it for when it's built on JS.

**Comment by denegny** [comment]
> This looks like an issue caused by the `youid` package, which is only used for the Erlang target, but I'm not sure how to suppress it for when it's built on JS.

> This is a basic [memoization](https://en.wikipedia.org/wiki/Memoization) method for Gleam on both the Erlang and Javascript targets, for caching and reusing the results of function calls when possible.

Javascript targets ))

**Comment by hunkyjimpjorps** [comment]
Like I said, it’s an issue with the package pulling in an Erlang-only requirement.  I don’t know how to stop it, so unless you can figure out how, you can ignore the warning.
